apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: els-password-generator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Elsgit1/els-password-generator.git
    targetRevision: main
    path: k8s-deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: els-password-generator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
